<?php
/**
 * Created by PhpStorm.
 * User: GTX
 * Date: 2017/4/24
 * Time: 20:45
 */

namespace app\index\controller;
use think\Controller;

class Base extends controller
{
    public function _initialize()
    {
        //parent::_initialize(); // TODO: Change the autogenerated stub
        $auntdata = session('aunt_username');
        $userdata = session('user_username');
        $this -> assign('aunt_name',$auntdata);
        $this -> assign('user_name',$userdata);//向前端传用户登录之后的相关信息
    }
}