<?php
/**
 * Created by PhpStorm.
 * User: GTX
 * Date: 2017/4/24
 * Time: 20:45
 */

namespace app\index\controller;
use think\Controller;
use app\admin\model\Cate;
class Base extends controller
{
    public function _initialize()
    {
        $Cate = new Cate();
        //parent::_initialize(); // TODO: Change the autogenerated stub
        $auntdata = session('aunt_username');
        $userdata = session('user_username');
        $this -> assign('aunt_name',$auntdata);
        $this -> assign('user_name',$userdata);//向前端传用户登录之后的相关信息
        //获取分类信息
        $catelist = $Cate -> getCateList(0);
        $this -> assign('catelist',$catelist);
        //分类信息获取end
    }
}